spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 465
    username:
    password:
    ssl:
      enabled: true

logging:
  level:
    root: info
    sql: info
    web: info
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB