spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_guard
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 465
    username:
    password:
    ssl:
      enabled: true

logging:
  level:
    root: info
    sql: debug
    web: debug
    org.springframework.security: debug
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      clean-history-on-start: true

jwt:
  issuer: ${spring.application.name}
  secret: Iufzg3THuUEyDUbQgILr5CJEQDX1vUyR4+wjYHjtUP0=
  access:
    token:
      expiry: 3600
  refresh:
    token:
      expiry: 86400